#' Set Y Axises for Line Split Plot
#'
#' It's hard to set y axises in the plot made by lines_split, since you don't know how many
#' y axises it has. This function is designed to help in setting those y axises.
#'
#' This function inherit from lines_split and add options to set y axises.
#'
#' @param p: a plotly object generated by the inner function lines_split, where
#' lines_split takes all the previous parameters to generate a basic plot
#' @param ... other parameters to set layout, usually options for yaxis. See "Details" for
#' more information
#' @export
#' @seealso \code{\link[plotly]{layout}},\code{\link{lines_split}}
#' @return This function will return an object of class plotly. By calling the function you
#' will get a plot with each subplot represent a line plot of a variable.
#' @usage lines_split_plot(p=lines_split(dataframe,ctg.idx,num.idx,condition,condition.idx,
#'                         colors,mode='lines',yaxis_name="",linewidth=2,title,...),...)
#' @examples
#' data("macro_data_chn")
#' lines_split_plot(p=lines_split(dataframe=macro_data_chn,ctg.idx = 'year',
#'                               num.idx = c(3,5,6,9),
#'                               colors=c("#00526d","#de6e6e","#32ab60","#ff8000"),
#'                               title="一些宏观经济指标走势",
#'                               xaxis=list(showgrid=F,ticklen=4,nticks=3,title="年份"),
#'                               legend=list(x=0.5,y=1.05,orientation='h',bgcolor='transparent'),
#'                               paper_bgcolor='#ccece6',margin=list(t=32,l=32,r=32)),
#'                  yaxis=list(visible=F),yaxis2=list(visible=F),
#'                  yaxis3=list(visible=F),yaxis4=list(visible=F))
#' lines_split_plot(p=lines_split(dataframe=macro_data_chn,ctg.idx = 'year',
#'                               num.idx = c(3,5,6,9),
#'                               colors=c("#00526d","#de6e6e","#32ab60","#ff8000"),
#'                               title="一些宏观经济指标走势",
#'                               xaxis=list(showgrid=F,ticklen=4,nticks=3,title="年份"),
#'                               legend=list(x=0.5,y=1.05,orientation='h',bgcolor='transparent'),
#'                               paper_bgcolor='#ccece6',margin=list(t=32,l=32,r=32)))

lines_split_plot=function(p=lines_split(dataframe,ctg.idx,num.idx,condition,condition.idx,
                                         colors,mode='lines',yaxis_name="",linewidth=2,
                                         title,...),...){
  p=p%>%layout(...)

  return(p)
}



