#' Transform nominal categorical variable into numerical variable
#'
#' Transform a nominal categorical column into multiple numerical columns with dummies,
#' can based on customer specified rule.
#'
#' The function will match each element in a categorical variable with a numeric value
#' by the mapping rule specified in the function input.
#'
#'
#' @param dataframe: a dataframe-like object
#' @param col.id: a vector of integers, specify which column in the dataframe
#' that you need to transfer
#' @param col.name: a vector of characters, another way to specify
#' the to-be-transformed column, will be disregarded if col.id is specified
#' @param drop: tells the function which dummied column you want to drop. The dropped one
#' will be served as the baseline in like regression model. Can be missed.
#' @export
#' @return a dataframe of dummy variables generated by choosen columns from original dataframe
#' @usage nom_ctg2num(dataframe,col.id,col.name=NA,drop)
#' @seealso \code{\link[dummies]{dummy}}
#' @examples
#' data(tmall_milk_sales)
#' test_df=tmall_milk_sales
#' nom_ctg2num(test_df,col.id=c(1,2,3,4,5))
#' nom_ctg2num(test_df,col.name=c('label','promotion'),drop=c('H','N'))
#' \dontrun{
#'   # be careful when having NAs, it will be treated as a new dummy
#'   test_df$label[12:15]=NA
#'   nom_ctg2num(test_df,col.name='label',drop='H')
#' }

nom_ctg2num=function(dataframe,col.id,col.name=NA,drop){
  if(missing(col.id)){
    col.id=match(col.name,colnames(dataframe))
  }

  df_copy=as.data.frame(dataframe[,col.id])
  colnames(df_copy)=col.id

  dummy_dataframe = dummy::dummy(df_copy)

  if(missing(drop)){
    elements=sapply(df_copy,MARGIN=2,unique)
    drop=unname(unlist(lapply(elements,'[[',1)))
  }else{
    drop=drop
  }

  drop.col=diag(as.matrix(sapply(col.id,function(chr1,chr2){paste0(chr1,chr2)},drop)))
  dummy_dataframe=dummy_dataframe[,!(colnames(dummy_dataframe)%in%drop.col)]

  return(dummy_dataframe)
}
