#' Stepwise Numerical Variable Selection for Panel Linear Regression
#'
#' \code{plm_basic} applied forward stepwise variable selection for panel data linear
#' regression. It can serve as a baseline for further model selection
#'
#' The function works like this: it start with the regression formula that contains only
#' all control variables. A model selection function will be applied
#' to determine which model among the three ('OLS','fixed effect','random effect') shall
#' be used. Then at each step, all possible variables, start with variables indicated by
#' "num.idx", will be add to the fourmula one at a time. For each time, the same  model
#' selection function will be applied to determine which model should be used, and the
#' p-value of the new variable adding to the formula in the selected model will be record.
#' Then for all the possible variables in this step, the one with smallest p-value, i.e. the
#' one which is the most significant variable among all possible choice will be add to
#' the formula permentately. It will then be eliminated from possible options that may
#' be add to the formula, and the corresponding model will be record for output. This loop
#' will be ran "step" times and a list containing "step"+1 models will be output as a list,
#' together with a summary table generated by \code{\link{stargazer}}. This is the standard
#' way for doing explorational panel regression. Note that since
#' within model will eliminate time invariant variables, the 'num.idx' should only contain
#' those variables that varied by time. Meanwhile, since it's a stepwise selection method,
#' dummy variable generated by nominal categorical variables with more than two levels should
#' also be avoided in "num.idx". For the summary table generated by stargazer looks clearly
#' in RStudio, we suggest steps less than or equal to 6, although one can have larger "step"
#' up to the length of "num.idx"
#'
#' @param dataframe: a dataframe object
#' @param id.idx: a string or an integer, indicate which column of the dataframe will be used
#' as individual index in panel dataframe
#' @param t.idx: a string or an integer, indicate which column of the dataframe will be used
#' as time index in panel dataframe
#' @param dep.idx: a string or an integer, indicate which column of the dataframe will be used
#' as the dependent variable, i.e. y, in the regression function
#' @param control.idx: a vector of strings or integers, but not both, indicate which column(s)
#' of the dataframe will be used as control variables in regression function
#' @param num.idx: a vector of strings or integers, but not both, indicate which column(s) of
#' the dataframe will be used as independent variables of interest in regression function.
#' See "Details" for more information
#' @param step: how many forward steps should be made. See "Details" for more information
#' @export
#' @usage plm_basic(dataframe,id.idx,t.idx,dep.idx,control.idx,num.idx,step)
#' @return A table that shows the summary information of all selected panel linear regression
#' models as well as a list containing all this models for further exploration.
#' @seealso \code{\link[plm]{plm}}
#' @author Jizhou Kang \email{jizhou_kang@@hotmail.com}
#' @references Jeffrey M. Wooldridge Introductory Econometrics: A Modern Approach,
#' Fifth edition
#' James Lee Ray, What Should Be Controlled for?(2003),
#'  \emph{Conflict Management and Peace Science}, Volume 20;1
#'  DOI: 10.1177/07388942032000201
#' @examples
#' data("estate_fin_charts")
#' estate_fin_charts$lg_asset=log(estate_fin_charts$asset)
#' model.list=plm_basic(dataframe=estate_fin_charts,id.idx=3,t.idx='Year',dep.idx='lg_income',
#'                      control.idx=c('mkt_price','lg_asset'),
#'                      num.idx=c(5,6,7,8,10,11,14,15),step=5)



plm_basic = function(dataframe,id.idx,t.idx,dep.idx,control.idx,num.idx,step){

  model_selection=function(formula){
    pooling=plm(formula,model='pooling',data=pdataframe)
    fixed=plm(formula,model='within',data=pdataframe)
    random=plm(formula,model='random',data=pdataframe)

    test1=plmtest(pooling)
    if(test1$p.value<0.05){
      test2=phtest(random,fixed)
      if(test2$p.value<0.05){
        model=fixed
      }else{
        model=random
      }
    }else{
      test2=pFtest(fixed,pooling)
      if(test2$p.value<0.05){
        model=fixed
      }else{
        model=pooling
      }
    }
    return(model)
  }

  step_forward=function(dep,original,pool){
    step.info=list()
    p.vec=c()
    i=1
    for(new.var in pool){
      indep.all=paste(c(original,new.var),collapse='+')
      formula=paste(dep,'~',indep.all,sep='')
      formula=as.formula(formula)
      model=model_selection(formula)
      p.value=summary(model)$coefficients[new.var,4]
      summarize.info=list()
      summarize.info$model=model
      summarize.info$var=new.var
      p.vec=c(p.vec,p.value)
      step.info[[i]]=summarize.info
      i=i+1
    }

    S=which.min(p.vec)

    result=list()
    result$new.model=step.info[[S]]$model
    result$new.original=c(original,step.info[[S]]$var)
    result$new.pool=pool[pool!=step.info[[S]]$var]

    return(result)
  }


  if(id.idx%in%colnames(dataframe)){
    id.idx=id.idx
  }else{
    id.idx=colnames(dataframe)[id.idx]
  }

  if(t.idx%in%colnames(dataframe)){
    t.idx=t.idx
  }else{
    t.idx=colnames(dataframe)[t.idx]
  }

  if(dep.idx%in%colnames(dataframe)){
    dep.idx=dep.idx
  }else{
    dep.idx=colnames(dataframe)[dep.idx]
  }

  if(control.idx[1]%in%colnames(dataframe)){
    control.idx=control.idx
  }else{
    control.idx=colnames(dataframe)[control.idx]
  }

  if(num.idx[1]%in%colnames(dataframe)){
    num.idx=num.idx
  }else{
    num.idx=colnames(dataframe)[num.idx]
  }


  pdataframe=pdata.frame(dataframe,index=c(id.idx,t.idx))

  selected.model=list()

  indep.all.ori=paste(control.idx,collapse ='+')
  formula.ori=paste(dep.idx,'~',indep.all.ori,sep='')
  formula.ori=as.formula(formula.ori)

  model.ori=model_selection(formula.ori)
  selected.model[[1]]=model.ori

  k=2
  original_cur=control.idx
  pool_cur=num.idx
  for(j in 1:step){
    new_step=step_forward(dep.idx,original_cur,pool_cur)
    original_cur=new_step$new.original
    pool_cur=new_step$new.pool
    selected.model[[k]]=new_step$new.model
    k=k+1
  }

  stargazer(selected.model,type='text',df=FALSE,
            title=paste('Models with most significant variables up to',step))

  return(selected.model)

}
